rm(list = ls())
setwd("/home/shlee101/FLCCM/2_Classification/")

source("setup - packages.R")
source("Code/000 - construct data for RF.R")
source("Code/100 - train crop1.R")
source("Code/200 - train crop2.R")
source("Code/300 - post processing+release.R")
source("Code/301 - Figure4_6_7.R")
source("Code/400 - kern.R")
source("Code/401 - Figure8.R")
source("Code/500 - Figure1_2_LandIQ2016.R")
source("Code/500 - Figure3_example grape fields.R")
source("Code/500 - Figure5_average total acre by crop and type.R")
source("Code/500 - Figure9_acreage of crop123,NASS,CDFA.R")